appname: "erutestapp"
entrypoints:
    showenv:
        cmd: "python show_env.py"
    runanddie:
        cmd: "python runanddie.py"
    show:
        cmd: "python show.py zzzzzz"
build: "echo 1"
volumes:
    - "/mnt/files"
binds:
    /mnt/mfs:
        bind: "/mnt/files"
        ro: true
