appname: "erutestapp"
entrypoints:
    showenv:
        cmd: "python show_env.py"
    runanddie:
        cmd: "python runanddie.py"
    algalon:
        cmd: "python algalon.py"
    show:
        cmd: "python show.py zzzzzz"
    web:
        cmd: "python web.py"
        ports:
            - "5000/tcp"
build:
    - "pip install requests"
volumes:
    - "/mnt/files"
binds:
    /mnt/mfs:
        bind: "/mnt/files"
        ro: true
