appname: "erutestapp"
entrypoints:
    showenv:
        cmd: "python show_env.py"
    runanddie:
        cmd: "python runanddie.py"
    algalon:
        cmd: "python algalon.py"
    show:
        cmd: "python show.py zzzzzz"
build:
    - "pip install requests"
    - "pip install httpie"
    - "http 216.58.221.132 --timeout 1000000"
volumes:
    - "/mnt/files"
binds:
    /mnt/mfs:
        bind: "/mnt/files"
        ro: true
